// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdn80Batp6Ig7HUPuJ18VxL7CLDiCZzIg',
    appId: '1:274987323558:web:aecf42d465f8a8b13de467',
    messagingSenderId: '274987323558',
    projectId: 'nightup-firebase',
    authDomain: 'nightup-firebase.firebaseapp.com',
    storageBucket: 'nightup-firebase.firebasestorage.app',
    measurementId: 'G-31JM3HJBCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx70xcYzqKWM4qPfgfC2xQCocw5Nv669I',
    appId: '1:274987323558:android:b7dfd9f222bfc9ba3de467',
    messagingSenderId: '274987323558',
    projectId: 'nightup-firebase',
    storageBucket: 'nightup-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kZZT4D_kGHlOpXNR6vUYsCPw8kHpPZE',
    appId: '1:274987323558:ios:e45f4eb2503c583e3de467',
    messagingSenderId: '274987323558',
    projectId: 'nightup-firebase',
    storageBucket: 'nightup-firebase.firebasestorage.app',
    iosBundleId: 'com.example.eaSeminari9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_kZZT4D_kGHlOpXNR6vUYsCPw8kHpPZE',
    appId: '1:274987323558:ios:e45f4eb2503c583e3de467',
    messagingSenderId: '274987323558',
    projectId: 'nightup-firebase',
    storageBucket: 'nightup-firebase.firebasestorage.app',
    iosBundleId: 'com.example.eaSeminari9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdn80Batp6Ig7HUPuJ18VxL7CLDiCZzIg',
    appId: '1:274987323558:web:a38a8ddcb6a30b583de467',
    messagingSenderId: '274987323558',
    projectId: 'nightup-firebase',
    authDomain: 'nightup-firebase.firebaseapp.com',
    storageBucket: 'nightup-firebase.firebasestorage.app',
    measurementId: 'G-LBQNVKP7B4',
  );
}
