name: nightup_mobile_app
description: "Nightup - Night events platform."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # CORE & UI
  get: ^4.6.5
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.0
  animations: ^2.0.11
  
  # MAPAS
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  table_calendar: ^3.0.9

  # AUTH & NETWORK
  google_sign_in: ^6.2.1
  firebase_auth: ^6.1.2
  firebase_auth_web: ^6.1.0
  firebase_core: ^4.2.1
  firebase_core_web: ^3.3.0
  firebase_messaging: ^16.0.4
  firebase_messaging_web: ^4.1.0
  js: ^0.6.3
  http: ^1.1.0
  dio: ^5.4.0
  socket_io_client: ^3.1.3
  pretty_dio_logger: ^1.3.1

  # UTILS
  geolocator: ^10.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  
  # Localizations
  flutter_translate: ^3.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # UI Utilities
  pull_to_refresh: ^2.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  
  # Validation
  password_strength_checker: ^1.3.2
  
  # Others
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  permission_handler: ^11.2.0
  flutter_dotenv: ^5.1.0

  # NUEVAS PARA POSTS Y FEEDS
  video_player: ^2.8.2
  chewie: ^1.7.0
  visibility_detector: ^0.4.0+2
  photo_view: ^0.14.0
  extended_image: ^7.0.1
  like_button: ^2.0.7
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/animations/
    - assets/images/default-avatar.png
    - assets/images/default-cover.jpg
    - assets/images/default-event.jpg
    - assets/images/default-business.jpg
    - assets/images/google.png
    - assets/images/default-mapa.jpg
    - assets/.env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

